name: flutter_translator
description: "A new Flutter project."

# Impede a publicação acidental no pub.dev.
publish_to: 'none' # Remova esta linha se desejar publicar.

# Versão do app: major.minor.patch+build
version: 1.0.0+1

# Ambiente SDK exigido
environment:
  sdk: ^3.7.2

# Dependências do projeto
dependencies:
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.1.2
  translator: ^1.0.3+1
  cupertino_icons: ^1.0.8

# Dependências apenas para desenvolvimento e testes
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/translator_logo.png"

# Configuração específica para Flutter
flutter:
  # Inclui a fonte de ícones padrão do Material Design
  uses-material-design: true

  # Para adicionar assets (como imagens), descomente e edite abaixo:
  assets:
    - assets/img/translator_logo.png
  # Para adicionar fontes personalizadas, edite o bloco abaixo:
  # fonts:
  #   - family: NomeDaFonte
  #     fonts:
  #       - asset: fonts/NomeDaFonte-Regular.ttf
  #       - asset: fonts/NomeDaFonte-Bold.ttf
  #         weight: 700
